on: [push]

name: Deploy ARM Template

env:
  LOCATION: westeurope
  RESOURCE_GROUP: rg-test

jobs:

  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Azure CLI magic
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group create --location $LOCATION --name $RESOURCE_GROUP
          az group deployment create --resource-group $RESOURCE_GROUP --template-file $GITHUB_WORKSPACE/azuredeploy.json