on: 
  push:
    branches:
      - master
name: Deploy ARM Template

env:
  LOCATION: westeurope
  RESOURCE_GROUP: rg-production-action

jobs:
  deploy-arm-template:
    runs-on: ubuntu-latest
    name: Deploy ARM Template
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Azure CLI Deploy ARM Template
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group create --location $LOCATION --name $RESOURCE_GROUP
          az group deployment create --resource-group $RESOURCE_GROUP --template-file $GITHUB_WORKSPACE/azuredeploy.json