on: [push]

name: Deploy ARM Template

jobs:

  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group create --location westeurope --name rg-test
          az deployment create --resource-group rg-test --template-file $GITHUB_WORKSPACE/azuredeploy.json --location westeurope